export { default as BackofficeHeader } from './BackofficeHeader'
export { default as BackofficeLayout } from './BackofficeLayout'
export { default as DashboardLayout } from './DashboardLayout'
export { default as IndoorLayout } from './IndoorLayout'
export { default as PageContainer } from './PageContainer'
export { default as ViewLayout } from './ViewLayout'